## Name: Amey Shendre
## Batch: A-A2-26

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Titanic-Dataset.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.shape

(891, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
#Correlation between variables
corr = df.corr()
corr.Survived.sort_values(ascending = False).head(10)

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'

In [ ]:
df["Embarked"].unique()

In [ ]:
df["Embarked"] = df["Embarked"].replace("S", 0)
df["Embarked"] = df["Embarked"].replace("C", 1)
df["Embarked"] = df["Embarked"].replace("Q", 2)

In [ ]:
df.isnull().sum()

In [ ]:
df["Age"].fillna(df["Age"].median(), inplace = True)

In [ ]:
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace = True)

In [ ]:
df.isnull().sum()

In [ ]:
df.drop("Cabin", axis = 1, inplace = True)

In [ ]:
df.duplicated().sum()

In [ ]:
df.head()

In [ ]:
sns.boxplot(x = df["Age"])

In [ ]:
sns.boxplot(x = df["Fare"])

In [ ]:
plt.figure(figsize = (14, 8))
df['Sex'].value_counts().plot(kind = "pie", autopct = "%.2f")

In [ ]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["Fare"] >= lower) &(df["Fare"] <= upper)]

In [ ]:
le = LableEncoder()

df["Sex"] = le.fit_transform(df["Sex"]

In [ ]:
df["Sex"] = df["Sex"].replace("male", 0)
df["Sex"] = df["Sex"].replace("female", 1)

In [ ]:
df.head()

In [ ]:
df = pd.get_dummies(df, columns = ["Embarked"])

In [ ]:
sns.histplot(df["Age"], kde = True)

In [ ]:
sns.countplot(x="Survived", data = df)

In [ ]:
sns.countplot(x="Sex", hue="Survived", data = df)

In [ ]:
sns.scatterplot(x = "Age", y = "Fare", data = df)

In [ ]:
plt.figure(figsize = (10,8))

numeric_df = df.select_dtypes(include = ['number'])

sns.heatmap(numeric_df.corr(),annot = True, cmap = 'coolwarm')

In [ ]:
sns.pairplot(df)

In [ ]:
scaler = StandardScaler()

df[["Age","Fare"]] = scaler.fit_transform(df[["Age","Fare"]])

In [ ]:
df.head()

In [ ]:
X = df.drop("Survived", axis = 1)

y = df["Survived"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)